<h3>Name: K Lalith Aditya</h3>
<h3>Class : 1 MSC</h3>
<h3>Regd No: 22231</h3>
<h3>Pandas Assignment</h3>

In [1]:
import pandas as pd
import numpy as np

# 1.Createing Series from numpy array , list, dict

In [42]:
mylist = list('wgnbwrgrhgbrhbg') # creating a list 
myarr  = np.arange(len(mylist))  # creating an array
mydict = dict(zip(myarr,mylist)) # creating a dictionary with keys as myarr and values as mylist

mySer1 = pd.Series(mylist) # creating Series from list
mySer2 = pd.Series(myarr)  # creating Series from array
mySer3 = pd.Series(mydict)  # creating Series from dictionary
print(mySer3.head())
print(mySer3.head())
print(mySer3.head())

0    w
1    g
2    n
3    b
4    w
dtype: object
0    w
1    g
2    n
3    b
4    w
dtype: object
0    w
1    g
2    n
3    b
4    w
dtype: object


# 2.Coverting Series index to a column in a Data Frame

In [46]:
mylist = list('sdgbbgwbvgeywvguvwegyv') # creating a list
myarr = np.arange(len(mylist))  # creating an array
mydict = dict(zip(mylist,myarr)) # creating a dictionary

mySeries = pd.Series(mydict)

df = mySeries.to_frame().reset_index()  # Series are converted to DataFrame
df['index']=['a','b','c','d','e','f','g','h','n']  
df

index   0
0     a   0
1     b   1
2     c  19
3     d   7
4     e  17
5     f  21
6     g  18
7     h  20
8     n  15

# 3.How to combine many series to form a dataframe?

In [47]:
mylist = list('afueuigbeuigiuebgiuebg') # list
myarr = np.arange(len(mylist)) # array

ser1 = pd.Series(mylist) # series from list
ser2 = pd.Series(myarr) # series from array

df = pd.DataFrame({'col1':ser1,'col2':ser2})  # Data Frame with column names as col1 and col2 and values of ser1 and ser2
df2 = pd.concat([ser1,ser2],axis=1) # Data Frame where we concat both series 

print(df.head())
print("\n")
print(df2.head())

  col1  col2
0    a     0
1    f     1
2    u     2
3    e     3
4    u     4


   0  1
0  a  0
1  f  1
2  u  2
3  e  3
4  u  4


# 4.How to assign name to the series’ index?

In [49]:
#print(ser1)

ser1.name = 'sairam' # assigning a name to the series
print(ser1)

0     a
1     f
2     u
3     e
4     u
5     i
6     g
7     b
8     e
9     u
10    i
11    g
12    i
13    u
14    e
15    b
16    g
17    i
18    u
19    e
20    b
21    g
Name: sairam, dtype: object


# 5.How to get the items of series A not present in series B?


In [53]:
ser1 = pd.Series(list('asfeubfeubibgeiubgujeb')) # series 1
ser2 = pd.Series(list('asfeubfzzzzzzzzzgujeb')) # series 2

ser1[~ser1.isin(ser2)] # First taking all values of ser1 present in ser2 and negating then displaying

10    i
14    i
dtype: object

# 6.How to get the items not common to both series A and series B?

In [54]:
ser1 = pd.Series(list('asfeubfeubibgeiubgujeb')) # series A
ser2 = pd.Series(list('asfeubfzzzzzzzzzgujeb')) # series B

union = pd.Series(np.union1d(ser1,ser2)) # taking the union of both series
intersect = pd.Series(np.intersect1d(ser1,ser2)) # taking intersection of both series
union[~union.isin(intersect)] # first taking union elements in intersection then not considering them in the union which gives items not common to both series A and B

5    i
9    z
dtype: object

# 7.How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [60]:
state = np.random.RandomState(100)  

ser = pd.Series(state.normal(10,5,25))#(parameters are mean ,sd,size)
a = np.percentile(ser, q=[0,25,50,75,100]) # from the series we are taking the 0,25,50,75,100 percentile points into a
a

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

# 8. How to get frequency counts of unique items of a series?

In [67]:
ser = pd.Series(np.take(list('abcfdefgh'), np.random.randint(8, size=30))) # we are taking a list and random.randint of size =30 
ser.value_counts() # we are checking the value counts for the list in the series

f    13
a     6
b     3
d     2
e     2
c     2
g     2
dtype: int64

# 9. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [73]:
np.random.RandomState(100) # np.random.RandomState
ser = pd.Series(np.random.randint(1, 5, [12])) # creating a series with random values 

print("Top 2 Freq:", ser.value_counts()) # printng the calue counts for a series
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other' # taking the top 2 most frequent values and making everything as 'Others'
ser

Top 2 Freq: 1    6
3    2
2    2
4    2
dtype: int64


0         3
1     Other
2         1
3         1
4         3
5     Other
6         1
7         1
8     Other
9     Other
10        1
11        1
dtype: object

# 10.How to bin a numeric series to 10 groups of equal size?

In [75]:
ser = pd.Series(np.random.random(20)) # random series of size=20
print(ser.head())

pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head() # parameters are the series and q is quantiles and labels for the corresponding quantiles

0    0.984780
1    0.000258
2    0.288723
3    0.358809
4    0.259464
dtype: float64


0    10th
1     1st
2     5th
3     6th
4     5th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

# 11. How to convert a numpy array to a dataframe of given shape? 

In [2]:
import numpy as np
import pandas as pd

In [76]:
ser = pd.Series(np.random.randint(1, 10, 35)) # creating a series starting from values 1 to 10 of 35 in number

ans = pd.DataFrame(ser.values.reshape(7,5)) # converting the series into Data frames of 7 rows and 5 columns
ans

0  1  2  3  4
0  2  3  4  5  3
1  4  6  5  8  8
2  6  4  3  6  5
3  6  4  6  4  2
4  1  9  6  4  8
5  1  9  5  4  3
6  1  5  6  7  8

# 12. How to import pandas and check the version?

In [37]:
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

1.4.3
{
  "system": {
    "commit": "e8093ba372f9adfe79439d90fe74b0b5b6dea9d6",
    "python": "3.9.13.final.0",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19044",
    "machine": "AMD64",
    "processor": "Intel64 Family 6 Model 23 Stepping 10, GenuineIntel",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "English_India",
      "encoding": "1252"
    }
  },
  "dependencies": {
    "pandas": "1.4.3",
    "numpy": "1.23.1",
    "pytz": "2022.1",
    "dateutil": "2.8.2",
    "setuptools": "58.1.0",
    "pip": "22.0.4",
    "Cython": null,
    "pytest": null,
    "hypothesis": null,
    "sphinx": null,
    "blosc": null,
    "feather": null,
    "xlsxwriter": null,
    "lxml.etree": null,
    "html5lib": null,
    "pymysql": null,
    "psycopg2": null,
    "jinja2": "3.1.2",
    "IPython": "8.4.0",
    "pandas_datareader": null,
    "bs4": "4.11.1",
    "bottleneck": null,
    "brotli": nu

# 13. How to extract items at given positions from a series

In [78]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz')) # creating a series
pos = [0,1, 4, 8, 16, 17] # list containing positions

ans = ser.take(pos) # from the list of positions we are taking correspoding values from the series
ans

0     a
1     b
4     e
8     i
16    q
17    r
dtype: object

# 14.How to stack two series vertically and horizontally ?

In [82]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('pqrs'))

# vertically
a = ser1.append(ser2) # if we do series.append the 2nd series will be made a continuation to series 1 so it becomes a single series
print(a)

# horizontally
df = pd.concat([ser1,ser2],axis=1) # if we do concat 2 series then it becomes a data frame with each of series as 1 column
df

0    0
1    1
2    2
3    3
4    4
0    p
1    q
2    r
3    s
dtype: object


C:\Users\Msc 1\AppData\Local\Temp\ipykernel_16856\3307822114.py:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a = ser1.append(ser2) # if we do series.append the 2nd series will be made a continuation to series 1 so it becomes a single series


0    1
0  0    p
1  1    q
2  2    r
3  3    s
4  4  NaN

# 15.How to get the positions of items of series A in another series B?


In [83]:
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

a=[pd.Index(ser1).get_loc(i) for i in ser2] # all elements are checked with the same elements in series 2 , if it is there then the locations of those elements are taken into the list
a

[5, 4, 0, 8]

# 16.How to compute the mean squared error on a truth and predicted series?

In [89]:
truth = pd.Series(range(10)) # series with values starting from 0 to 10
pred = pd.Series(range(10)) + np.random.random(10) # series with values starting from 0 to 10 and some random values are added to corresponding elements in the series

ans = np.mean((truth-pred)**2) # we take the meansquare error using numpy
ans

0.3120053848528359

# 17.How to convert the first character of each element in a series to uppercase?

In [90]:
ser = pd.Series(['how', 'to', 'kick', 'hard'])

pd.Series([i.title() for i in ser]) # We are making each element in the series as Title since Title starts with a capital letter

0     How
1      To
2    Kick
3    Hard
dtype: object

# 18.How to calculate the number of characters in each word in a series?

In [91]:
ser = pd.Series(['how','to','kick','hard']) # creating a series from a list

ser.map(lambda x: len(x))  # map module is used to operate with series elements , here we are taking the length of each element

0    3
1    2
2    4
3    4
dtype: int64

# 19.How to compute difference of differences between consequtive numbers of a series?

In [97]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff().tolist()) # we are calculating the difference b/w two consecutive numbers of a series
print(ser.diff().diff().tolist()) # we are calculating the difference b/w two consecutive numbers of a series


[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


# 20.How to convert a series of date-strings to a timeseries?

In [106]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse # from dateutil.parser module we import parse
ser.map(lambda x: parse(x)) # this parse will be used to convert the elements in the series to datetime format

pd.to_datetime(ser) # Given strings in the series will be converted to datetime type


0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

# 21.How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [107]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    5
2000-01-08    9
2000-01-15    8
2000-01-22    1
2000-01-29    1
2000-02-05    8
2000-02-12    2
2000-02-19    8
2000-02-26    2
2000-03-04    5
Freq: W-SAT, dtype: int32

# 22.How to convert year-month string to dates corresponding to the 4th day of the month?

In [108]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012']) # series of values containing month and year

from dateutil.parser import parse

# parse the date
ser_ts = ser.map(lambda x: parse(x)) # parsing the date into date time type

# construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# by formatting we get
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

ser.map(lambda x: parse('04' + x))


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

# 23.How to filter words that contain atleast 2 vowels from a series?

In [110]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money']) # creating a series from a list containing fruit names

from collections import Counter # Importing Counter from collections module
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')]) >=2) # This Counter will check the items in the Series where the elements contain atleast 2 vowels
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

# 24.How to filter valid emails from a series?

In [113]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

import re #re stands for regular expression
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

mask = emails.map(lambda x: bool(re.match(pattern,x))) # this will check the series elements in the pattern , if the elements contain Series values in pattern then those will be taken into the mask variable
emails[mask]


1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

# 25.How to get the mean of a series grouped by another series?

In [122]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10)) # creating a series of 10 values containing apple,banana,carrot
weights = pd.Series(np.linspace(1, 10, 10))

weights.groupby(fruit).mean() # We group weights series with fruit series and get the mean 

apple     7.000000
banana    5.500000
carrot    5.285714
dtype: float64

In [2]:
import numpy as np
import pandas as pd

# 26.How to compute the euclidean distance between two series?

In [5]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # creating a series p
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) # creating a series q


ans = np.linalg.norm(p-q) # using np.linalg we calculate the norm b/w 2 series
ans

18.16590212458495

# 27.How to find all the local maxima (or peaks) in a numeric series?

In [14]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3]) # creating a series


dd = np.diff(np.sign(np.diff(ser))) #  it is used when we calculate the n-th order discrete difference in the above series
peak_locs = np.where(dd == -2)[0] + 1 # if the difference is -2 then take that element into peak_locs variable
peak_locs

array([1, 5, 7], dtype=int64)

# 28.How to replace missing spaces in a string with the least frequent character?

In [15]:
my_str = 'dbc deb abed gade'  # string

ser = pd.Series(list('dbc deb abed gade')) # converting string into list and to series
freq = ser.value_counts() # taking frequency of items in the series
print(freq)  
least_freq = freq.dropna().index[-1] # in places of spaces replace them with items with less frequency
"".join(ser.replace(' ', least_freq))

d    4
b    3
     3
e    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

# 29.How to create a dataframe with rows as strides from a given series?

In [16]:
L = pd.Series(range(15)) # series L

def gen_strides(a, stride_len=5, window_len=5): 
    """
    Args: a : type list
          stride_len : type int
          window_len : type int
    Summary: Its used to create a data frame with rows as strides from a given series      
    """
    n_strides = ((a.size-window_len)//stride_len) + 1 # calculating n_strides
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

# 30. How to import only specified columns from a csv file?

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv']) # reading a csv file and selecting only 2 of them named(crim and medv) into the data frame
print(df.head()) # printing the top 5 rows in the data frame

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


# 31.How to check if a dataframe has any missing values?

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv') # reading a csv file
df.isnull().values.any() # checking any values which have null in the data frame

True

# 32.How to count the number of missing values in each column?

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')  # reading the csv file

n_missings_each_col = df.apply(lambda x: x.isnull().sum()) # in columns if null values are there we are counting them
n_missings_each_col.argmax() # returns the maximum missing value count in the column

23

# 33.How to replace missing values of multiple numeric columns with the mean?

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv') # reading a csv file

df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean())) # We are taking the min price and max price columns and whatever missing values are there we are replacing with mean of those columns
print(df_out.head()) # printing the first 5 rows of df_out data frame

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


# 34.How to filter every nth row in a dataframe?

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv') # reading a csv file

print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]) # printing every row with common difference = 20 , starting from 0th row

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


# 35.  How to create a primary key index by combining relevant columns?

In [11]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5]) # reading csv file and using the mentioned columns only from the file

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing') # filling missing values in columns Manufacturer, Model and Type
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type # calculating index
print(df.index.is_unique) # printing if index value is unique

True


# 36.How to get the row number of the nth largest value in a column?

In [17]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc')) #creating a data frame with 10 rows and 3 columns named('a','b','c')
# Solution
n = 5
df['a'].argsort()[::-1][n] # getting the rowth number for 5th largest value in that ath column

7

# 37.How to swap two rows of a dataframe?

In [25]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))  # creating a data frame with 5 rows and 5 columns with values from 0 to 25

def swap_rows(df, i1, i2):
    """
    Args: df - data frame
          i1 - row number that will swap with row i2 , type int
          i2 - row number with which row i1 gets swapped, type int
    Summary: This function will swap the rows i1,i2 for the given data frame and return the data frame
    """
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy() # copying the rows of data frame into a,b
    df.iloc[i1, :], df.iloc[i2, :] = b, a # swapping the rows of the data-frame
    return df # returning the data frame

print(swap_rows(df, 1, 2)) # we want to swap rows with index 1 and 2

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


# 38. How to reverse the rows of a dataframe?

In [26]:
df = pd.DataFrame(np.arange(25).reshape(5, -1)) # creating a data frame with 5 rows and 5 columns and values from 0 to 25

print(df.loc[df.index[::-1], :]) # reversing elements for each row-index

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


# 39.How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?

In [38]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)}) # creating a data-frame with 9 rows and 3 columns 
# First column has all fruit names , 2nd column has the rating , 3rd has price

out = df.groupby('fruit', as_index=False)['price'].mean() #each fruits mean price is calculated into an other data frame named out
print(out)

    fruit     price
0   apple  6.666667
1  banana  6.666667
2  orange  3.666667


# 40.How to get the positions where values of two columns match?

In [46]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# data frame with 2 columns named fruit 1 and fruit 2 with 3 fruit names 

a=np.where(df.fruit1 == df.fruit2) # where fruit 1 name and fruit 2 name are same in both columns at particular row take the row index into array and print it
a

(array([0, 2, 7], dtype=int64),)

# 41.How to create lags and leads of a column in a dataframe?

In [49]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd')) # creating a data frame with 5 rows and 4 columns with column names a,b,c,d

df['a_lag1'] = df['a'].shift(1) #creating lags from column a
df['b_lead1'] = df['b'].shift(-1) #creating leads from column b
print(df)


    a   b   c   d  a_lag1  b_lead1
0  49  92  81  19     NaN     11.0
1  69  11  24  80    49.0      1.0
2  20   1  41  47    69.0     94.0
3  70  94  76  43    20.0     57.0
4  40  57  55  74    70.0      NaN


# 42.How to get the frequency of unique values in the entire dataframe?

In [55]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd')) # creating 5 rows and 4 columns with column names a,b,c,d and values are from 1 to 10

pd.value_counts(df.values.ravel()) # counting the frequency of the unique values int the dataframe

6    5
8    4
3    3
7    3
5    2
9    1
4    1
2    1
dtype: int64

In [2]:
import numpy as np
import pandas as pd

# 43.How to find and cap outliers from a series or dataframe column?

In [6]:
ser = pd.Series(np.logspace(-2, 2, 30))  # creating a series with start =-2 and stop=2 , space =30 

def cap_outliers(ser, low_perc, high_perc):
    """
    Args: ser - series ,type- Series
          low_perc - low percentile, type - float
          high_perc - high percentile, type - float
    Summary:
            It will take outliers from the given series
    """
    low, high = ser.quantile([low_perc, high_perc]) # taking quantiles in the series into low and high
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high) # printing the values
    ser[ser < low] = low # series values less than low are equated to low
    ser[ser > high] = high  # series values greater than high are equated to high
    return(ser) # return series

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.87667222018393


# 44.How to reshape a dataframe to the largest possible square after removing the negative values?

In [8]:
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1)) # creating a data frame with 10 rows and 10 columns with values from -20 to 50 and 100 values
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()  # converting data frame into a list
arr_qualified = arr[~np.isnan(arr)] # what are  not a number in the list remove them and take the rest

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))   

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]  
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  48   2  12  44  23 -13  18 -17  18   0
1  18 -20  15  -4  45 -12  -7   5   7  -3
2   8  46 -19  33   8  -6  20  34  47  25
3  19  -5  34   2  -6  46  41  39 -16   7
4  36  43  11  22   1  24   2  26  26  -6
5  31  21  21 -14   7  14  -9  40  17  34
6 -17  49  44  43  28  21  42  45 -11  31
7  12  -4  14  17  39  -6  49  -3  30 -14
8  11  25  17  28  43  23  11 -17  43 -20
9  46   9 -16   8  18  21   3 -16   0  30
[[48. 12. 44. 23. 18. 18. 18. 15.]
 [45.  8. 46. 33.  8. 20. 34. 47.]
 [25. 19. 34. 46. 41. 39. 36. 43.]
 [11. 22. 24. 26. 26. 31. 21. 21.]
 [14. 40. 17. 34. 49. 44. 43. 28.]
 [21. 42. 45. 31. 12. 14. 17. 39.]
 [49. 30. 11. 25. 17. 28. 43. 23.]
 [11. 43. 46.  9.  8. 18. 21. 30.]]


# 45.How to create one-hot encodings of a categorical variable (dummy variables)?

In [18]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde')) # creating a data frame with 5 rows and 5 columns(a,b,c,d,e) and values are from 0 to 24

df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1) 
# We are creating dummy variables for column 'a' where values are nominal and concatenating the remaining b,c,d,e columns with that dummy columns
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


# 46.Which column contains the highest number of row-wise maximum values?

In [23]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1)) #Creating a data frame with 10 rows and 4 columns with random values from 1 to 100


print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0]) #printing the column which contains highest row-wise maximum values  

Column with highest row maxes:  3


# 47.How to know the maximum possible correlation value of each column against other columns?

In [37]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
#data frame with random values 1 to 100 and column names (p,q,r,s,t,u,v,w,x,y) and index values (a,b,c,d,e,f,g,h)

abs_corrmat = np.abs(df.corr()) # correlation matrix among columns which contains absolute values 
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2]) # calculating the max correlation for each column into list max_corr
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2)) #printing the max correlation with rounding to 2 decimal values

Maximum Correlation possible for each column:  [0.46 0.68 0.66 0.66 0.5  0.68 0.53 0.53 0.63 0.37]


# 48.How to create a column containing the minimum by maximum of each row?

In [48]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1)) # dataframe with 8 rows and 10 columns with random values from 1 to 100

min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1) # creating a column containing the minimum by maximum of each row
print(min_by_max) # printing the column

0    0.071429
1    0.080460
2    0.103896
3    0.077778
4    0.117647
5    0.173913
6    0.206897
7    0.232323
dtype: float64


# 49.How to create a column that contains the penultimate value in each row?

In [55]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1)) # data frame with 8 rows and 10 columns and random values from 1 to 100

out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1) #sorting and taking the penultimate value (2nd maximum value) from each row into the variable out 
df['penultimate'] = out #creating a column with name = penultimate and assigning values of out to that column into dataframe df
print(df)  

    0   1   2   3   4   5   6   7   8   9  penultimate
0  47   5  31  48  61  80  43  85  79  21           80
1  97   1  68  54  97  52   5  57   9  60           68
2  49  25  60  19  62  22  59  19  60  90           62
3  20   6  43  21  71  43  29  10  91  42           71
4  97  75  53   9  21  17  97  78  45  20           78
5  32   3  39  24  64  96  15  35  91  81           91
6  16  26  49  24  80   8  71  28  74  29           74
7  11  97  35  86  57  45  97  19  58  38           86


# 50.How to normalize all columns in a dataframe?

In [58]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1)) #creating a dataframe with 8 rows and 10 columns with random values 1 to 100

out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2)) # Normalizing all columns of df by subtracting the column mean and divide by standard deviation. 
print('Solution Q1\n',out1) # printing Q1 values
print()
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2)) # Taking range all columns of df such that the minimum value in each column is 0 and max is 1.
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -0.62 -0.56  0.25 -1.10  0.01  0.15 -1.23 -0.85  1.03  1.20
1 -0.76  1.17  1.24  0.98 -0.22 -1.77 -0.17  1.62 -0.16  1.20
2  0.55  1.44 -0.37  0.36  1.27  0.56 -0.81  1.03  0.01  0.14
3  1.21  0.67 -1.20 -0.70  0.75  1.47  0.89 -0.48  1.35 -0.37
4  1.21 -1.47 -0.73 -0.42  0.70 -1.06  0.57 -0.60  0.88 -0.66
5 -0.90 -0.29 -0.84 -1.29 -0.51  0.15  0.99  0.85 -1.24 -1.31
6 -1.28 -0.24  0.05  1.10  0.01  0.05  1.03 -0.60 -1.12  0.85
7  0.60 -0.70  1.60  1.07 -2.00  0.46 -1.28 -0.97 -0.74 -1.05

Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.74  0.69  0.48  0.92  0.39  0.41  0.98  0.95  0.12  0.00
1  0.79  0.09  0.13  0.05  0.46  1.00  0.52  0.00  0.58  0.00
2  0.26  0.00  0.70  0.31  0.00  0.28  0.80  0.23  0.52  0.42
3  0.00  0.27  1.00  0.75  0.16  0.00  0.06  0.81  0.00  0.62
4  0.00  1.00  0.83  0.64  0.18  0.78  0.20  0.86  0.18  0.74
5  0.85  0.59  0.87  1.00  0.54  0.41  0.02